export default [
  {
    input: true,
    components: [
      {
        input: true,
        label: 'Name',
        key: 'name',
        placeholder: 'Attribute Name',
        type: 'textfield'
      },
      {
        input: true,
        label: 'Value',
        key: 'value',
        placeholder: 'Attribute Value',
        type: 'textfield'
      }
    ],
    label: 'HTML Attributes',
    key: 'htmlAttributes',
    type: 'datagrid',
    tooltip: 'Provide a set of HTML attributes for component\'s input element (attributes provided by other component settings or other attributes generated by form.io take precedence over attributes in this grid)'
  }
];
