export class Rules {
    static rules: {
        custom: typeof Custom;
        date: typeof DateRule;
        day: typeof Day;
        email: typeof Email;
        json: typeof JSON;
        mask: typeof Mask;
        max: typeof Max;
        maxDate: typeof MaxDate;
        maxLength: typeof MaxLength;
        maxWords: typeof MaxWords;
        maxYear: typeof MaxYear;
        min: typeof Min;
        minDate: typeof MinDate;
        minLength: typeof MinLength;
        minWords: typeof MinWords;
        minYear: typeof MinYear;
        pattern: typeof Pattern;
        required: typeof Required;
        select: typeof Select;
        unique: typeof Unique;
        url: typeof Url;
        time: typeof Time;
    };
    static addRule(name: any, rule: any): void;
    static addRules(rules: any): void;
    static getRule(name: any): any;
    static getRules(): {
        custom: typeof Custom;
        date: typeof DateRule;
        day: typeof Day;
        email: typeof Email;
        json: typeof JSON;
        mask: typeof Mask;
        max: typeof Max;
        maxDate: typeof MaxDate;
        maxLength: typeof MaxLength;
        maxWords: typeof MaxWords;
        maxYear: typeof MaxYear;
        min: typeof Min;
        minDate: typeof MinDate;
        minLength: typeof MinLength;
        minWords: typeof MinWords;
        minYear: typeof MinYear;
        pattern: typeof Pattern;
        required: typeof Required;
        select: typeof Select;
        unique: typeof Unique;
        url: typeof Url;
        time: typeof Time;
    };
}
import { Custom } from "./Custom";
import { DateRule } from "./Date";
import { Day } from "./Day";
import { Email } from "./Email";
import { JSON } from "./JSON";
import { Mask } from "./Mask";
import { Max } from "./Max";
import { MaxDate } from "./MaxDate";
import { MaxLength } from "./MaxLength";
import { MaxWords } from "./MaxWords";
import { MaxYear } from "./MaxYear";
import { Min } from "./Min";
import { MinDate } from "./MinDate";
import { MinLength } from "./MinLength";
import { MinWords } from "./MinWords";
import { MinYear } from "./MinYear";
import { Pattern } from "./Pattern";
import { Required } from "./Required";
import { Select } from "./Select";
import { Unique } from "./Unique";
import { Url } from "./Url";
import { Time } from "./Time";
