declare var _default: ({
    key: string;
    ignore: boolean;
    type?: undefined;
    input?: undefined;
    weight?: undefined;
    label?: undefined;
    placeholder?: undefined;
    tooltip?: undefined;
    components?: undefined;
    editor?: undefined;
    rows?: undefined;
    as?: undefined;
    defaultValue?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    weight: number;
    label: string;
    placeholder: string;
    tooltip: string;
    ignore?: undefined;
    components?: undefined;
    editor?: undefined;
    rows?: undefined;
    as?: undefined;
    defaultValue?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    tooltip: string;
    weight: number;
    components: {
        label: string;
        key: string;
        input: boolean;
        type: string;
    }[];
    ignore?: undefined;
    placeholder?: undefined;
    editor?: undefined;
    rows?: undefined;
    as?: undefined;
    defaultValue?: undefined;
} | {
    type: string;
    input: boolean;
    editor: string;
    rows: number;
    as: string;
    label: string;
    tooltip: string;
    defaultValue: string;
    key: string;
    weight: number;
    ignore?: undefined;
    placeholder?: undefined;
    components?: undefined;
} | {
    weight: number;
    type: string;
    label: string;
    tooltip: string;
    key: string;
    input: boolean;
    ignore?: undefined;
    placeholder?: undefined;
    components?: undefined;
    editor?: undefined;
    rows?: undefined;
    as?: undefined;
    defaultValue?: undefined;
})[];
export default _default;
