declare var _default: ({
    type: string;
    title: any;
    theme: string;
    collapsible: boolean;
    collapsed: boolean;
    key: string;
    weight: any;
    components: any[];
} | {
    weight: number;
    type: string;
    label: string;
    tooltip: string;
    key: string;
    input: boolean;
    placeholder?: undefined;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    type: string;
    label: string;
    key: string;
    weight: number;
    placeholder: string;
    tooltip: string;
    input: boolean;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    weight: number;
    type: string;
    label: string;
    tooltip: string;
    key: string;
    input: boolean;
    inline: boolean;
    defaultValue: boolean;
    values: ({
        label: string;
        value: boolean;
    } | {
        label: string;
        value: string;
    })[];
    placeholder?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    weight: number;
    tooltip: string;
    dataSrc: string;
    valueProperty: string;
    data: {
        custom(context: any): {
            label: string;
            value: string;
        }[];
    };
    conditional: {
        json: {
            '!': {
                var: string;
            }[];
        };
    };
    placeholder?: undefined;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    weight: number;
    type: string;
    label: string;
    key: string;
    defaultValue: boolean;
    tooltip: string;
    input: boolean;
    placeholder?: undefined;
    inline?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    key: string;
    type: string;
    input: boolean;
    weight: number;
    tag: string;
    content: string;
    label?: undefined;
    tooltip?: undefined;
    placeholder?: undefined;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    validate?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    weight: number;
    type: string;
    input: boolean;
    key: string;
    label: string;
    tooltip: string;
    validate: {
        pattern: string;
        patternMessage: string;
    };
    placeholder?: undefined;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    storeas?: undefined;
    valueComponent?: undefined;
} | {
    weight: number;
    type: string;
    input: boolean;
    label: string;
    storeas: string;
    tooltip: string;
    key: string;
    placeholder?: undefined;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    valueComponent?: undefined;
} | {
    weight: number;
    type: string;
    label: string;
    tooltip: string;
    key: string;
    valueComponent: {
        type: string;
        key: string;
        label: string;
        placeholder: string;
        input: boolean;
    };
    input?: undefined;
    placeholder?: undefined;
    inline?: undefined;
    defaultValue?: undefined;
    values?: undefined;
    dataSrc?: undefined;
    valueProperty?: undefined;
    data?: undefined;
    conditional?: undefined;
    tag?: undefined;
    content?: undefined;
    validate?: undefined;
    storeas?: undefined;
})[];
export default _default;
