declare var _default: ({
    type: string;
    input: boolean;
    weight: number;
    tooltip: string;
    key: string;
    defaultValue: string;
    label: string;
    dataSrc: string;
    data: {
        values: {
            label: string;
            value: string;
        }[];
        url?: undefined;
    };
    conditional?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    weight: number;
    input: boolean;
    key: string;
    label: string;
    tooltip: string;
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    as: string;
    editor: string;
    weight: number;
    input: boolean;
    key: string;
    label: string;
    tooltip: string;
    defaultValue: {};
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    dataSrc?: undefined;
    data?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    as: string;
    editor: string;
    weight: number;
    input: boolean;
    key: string;
    label: string;
    tooltip: string;
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    weight: number;
    label: string;
    placeholder: string;
    tooltip: string;
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    tooltip: string;
    weight: number;
    conditional: {
        json: {
            in: (string[] | {
                var: string;
            })[];
            '==='?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    tooltip: string;
    weight: number;
    components: {
        label: string;
        key: string;
        input: boolean;
        type: string;
    }[];
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    tooltip: string;
    weight: number;
    reorder: boolean;
    defaultValue: {
        label: string;
        value: string;
    }[];
    components: ({
        label: string;
        key: string;
        input: boolean;
        type: string;
        allowCalculateOverride?: undefined;
        calculateValue?: undefined;
    } | {
        label: string;
        key: string;
        input: boolean;
        type: string;
        allowCalculateOverride: boolean;
        calculateValue: {
            _camelCase: {
                var: string;
            }[];
        };
    } | {
        key: string;
        label: string;
        type: string;
        input: boolean;
        dataSrc: string;
        groupProperty: string;
        data: {
            custom(args: any): any;
        };
        valueProperty: string;
        template: string;
        allowCalculateOverride?: undefined;
        calculateValue?: undefined;
    })[];
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    dataSrc: string;
    data: {
        url: string;
        values?: undefined;
    };
    authenticate: boolean;
    template: string;
    valueProperty: string;
    clearOnHide: boolean;
    label: string;
    key: string;
    lazyLoad: boolean;
    weight: number;
    tooltip: string;
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    weight: number;
    description: string;
    tooltip: string;
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    skipMerge: boolean;
    clearOnHide: boolean;
    tooltip: string;
    weight: number;
    refreshOn: string;
    template: string;
    valueProperty: string;
    dataSrc: string;
    lazyLoad: boolean;
    onSetItems(component: any, form: any): {
        label: string;
        key: string;
    }[];
    onChange(context: any): void;
    data: {
        url: string;
        values?: undefined;
    };
    conditional: {
        json: {
            and: ({
                '===': (string | {
                    var: string;
                })[];
                var?: undefined;
            } | {
                var: string;
                '==='?: undefined;
            })[];
            '==='?: undefined;
            in?: undefined;
        };
    };
    defaultValue?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    description?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    skipMerge: boolean;
    clearOnHide: boolean;
    tooltip: string;
    weight: number;
    refreshOn: string;
    template: string;
    valueProperty: string;
    dataSrc: string;
    lazyLoad: boolean;
    onSetItems(component: any, form: any): any[];
    data: {
        url: string;
        values?: undefined;
    };
    conditional: {
        json: {
            and: ({
                '===': (string | {
                    var: string;
                })[];
                var?: undefined;
            } | {
                var: string;
                '==='?: undefined;
            })[];
            '==='?: undefined;
            in?: undefined;
        };
    };
    defaultValue?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    description?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    clearOnHide: boolean;
    tooltip: string;
    weight: number;
    template: string;
    dataSrc: string;
    data: {
        values: {
            label: string;
            value: string;
        }[];
        url?: undefined;
    };
    defaultValue?: undefined;
    conditional?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    valueProperty?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    label: string;
    key: string;
    skipMerge: boolean;
    clearOnHide: boolean;
    weight: number;
    description: string;
    tooltip: string;
    conditional: {
        json: {
            in: (string[] | {
                var: string;
            })[];
            '==='?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    lazyLoad?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    weight: number;
    description: string;
    tooltip: string;
    conditional: {
        json: {
            in: (string[] | {
                var: string;
            })[];
            '==='?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    weight: number;
    label: string;
    tooltip: string;
    defaultValue: number;
    conditional: {
        json: {
            and: ({
                '===': (string | {
                    var: string;
                })[];
                '!='?: undefined;
            } | {
                '!=': (string | {
                    var: string;
                })[];
                '==='?: undefined;
            })[];
            '==='?: undefined;
            in?: undefined;
        };
    };
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    weight: number;
    defaultValue: number;
    description: string;
    tooltip: string;
    conditional: {
        json: {
            in: (string[] | {
                var: string;
            })[];
            '==='?: undefined;
            and?: undefined;
        };
    };
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    editor: string;
    rows: number;
    weight: number;
    placeholder: string;
    tooltip: string;
    conditional: {
        json: {
            '===': (string | {
                var: string;
            })[];
            in?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    editor: string;
    as: string;
    rows: number;
    weight: number;
    tooltip: string;
    allowCalculateOverride: boolean;
    calculateValue: (context: any) => any;
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    conditional?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    key: string;
    label: string;
    weight: number;
    tooltip: string;
    dataSrc: string;
    valueProperty: string;
    data: {
        custom(context: any): {
            label: string;
            value: string;
        }[];
        values?: undefined;
        url?: undefined;
    };
    conditional: {
        json: {
            in: (string[] | {
                var: string;
            })[];
            '==='?: undefined;
            and?: undefined;
        };
    };
    defaultValue?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    weight: number;
    key: string;
    label: string;
    defaultValue: boolean;
    tooltip: string;
    conditional: {
        json: {
            in: (string[] | {
                var: string;
            })[];
            '==='?: undefined;
            and?: undefined;
        };
    };
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    weight: number;
    key: string;
    label: string;
    defaultValue: boolean;
    tooltip: string;
    dataSrc?: undefined;
    data?: undefined;
    conditional?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    label: string;
    mask: boolean;
    tableView: boolean;
    alwaysEnabled: boolean;
    type: string;
    input: boolean;
    key: string;
    validate: {
        min: number;
        customMessage: string;
        json: string;
        max: number;
    };
    delimiter: boolean;
    requireDecimal: boolean;
    encrypted: boolean;
    defaultValue: number;
    weight: number;
    tooltip: string;
    dataSrc?: undefined;
    data?: undefined;
    conditional?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
} | {
    type: string;
    label: string;
    key: string;
    tooltip: string;
    placeholder: string;
    weight: number;
    input: boolean;
    conditional: {
        json: {
            and: ({
                '===': (string | {
                    var: string;
                })[];
                '!!'?: undefined;
            } | {
                '!!': {
                    var: string;
                };
                '==='?: undefined;
            })[];
            '==='?: undefined;
            in?: undefined;
        };
    };
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    as?: undefined;
    editor?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    input: boolean;
    weight: number;
    key: string;
    label: string;
    tooltip: string;
    defaultValue?: undefined;
    dataSrc?: undefined;
    data?: undefined;
    conditional?: undefined;
    as?: undefined;
    editor?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
} | {
    type: string;
    as: string;
    editor: string;
    weight: number;
    input: boolean;
    key: string;
    label: string;
    tooltip: string;
    defaultValue: {};
    dataSrc?: undefined;
    data?: undefined;
    conditional?: undefined;
    placeholder?: undefined;
    components?: undefined;
    reorder?: undefined;
    authenticate?: undefined;
    template?: undefined;
    valueProperty?: undefined;
    clearOnHide?: undefined;
    lazyLoad?: undefined;
    description?: undefined;
    skipMerge?: undefined;
    refreshOn?: undefined;
    onChange?: undefined;
    rows?: undefined;
    allowCalculateOverride?: undefined;
    calculateValue?: undefined;
    mask?: undefined;
    tableView?: undefined;
    alwaysEnabled?: undefined;
    validate?: undefined;
    delimiter?: undefined;
    requireDecimal?: undefined;
    encrypted?: undefined;
})[];
export default _default;
