module.exports = {
  title: 'Simple Wizard',
  form: {
    _id: '58cdd541d482d500aaf48368',
    machineName: 'eguamgudzerbvzc:wizard',
    modified: '2017-03-19T00:48:02.035Z',
    title: 'Wizard',
    display: 'wizard',
    name: 'wizard',
    path: 'wizard',
    project: '58cc056767cb9600a75712e2',
    created: '2017-03-19T00:48:01.666Z',
    components: [{
      key: 'panel1',
      input: false,
      title: 'Page 1',
      theme: 'default',
      components: [{
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'a',
        key: 'a',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        clearOnHide: true,
        validate: {required: false, minLength: '', maxLength: '', pattern: '', custom: '', customPrivate: false},
        conditional: {show: '', when: null, eq: ''},
        type: 'textfield',
        tags: []
      }, {
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'b',
        key: 'b',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        clearOnHide: true,
        validate: {required: false, minLength: '', maxLength: '', pattern: '', custom: '', customPrivate: false},
        conditional: {show: '', when: null, eq: ''},
        type: 'textfield',
        tags: []
      }],
      type: 'panel',
      tags: [],
      conditional: {show: '', when: null, eq: ''}
    }, {
      key: 'panel2',
      input: false,
      title: 'Page 2',
      theme: 'default',
      components: [{
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'c',
        key: 'c',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        clearOnHide: true,
        validate: {required: false, minLength: '', maxLength: '', pattern: '', custom: '', customPrivate: false},
        conditional: {show: '', when: null, eq: ''},
        type: 'textfield',
        tags: []
      }, {
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'd',
        key: 'd',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        clearOnHide: true,
        validate: {required: false, minLength: '', maxLength: '', pattern: '', custom: '', customPrivate: false},
        conditional: {show: '', when: null, eq: ''},
        type: 'textfield',
        tags: []
      }],
      type: 'panel',
      tags: [],
      conditional: {show: '', when: null, eq: ''}
    }, {
      key: 'panel3',
      input: false,
      title: 'Page 3',
      theme: 'default',
      components: [{
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'e',
        key: 'e',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        clearOnHide: true,
        validate: {required: false, minLength: '', maxLength: '', pattern: '', custom: '', customPrivate: false},
        conditional: {show: '', when: null, eq: ''},
        type: 'textfield',
        tags: []
      }, {
        input: true,
        tableView: true,
        inputType: 'text',
        inputMask: '',
        label: 'f',
        key: 'f',
        placeholder: '',
        prefix: '',
        suffix: '',
        multiple: false,
        defaultValue: '',
        protected: false,
        unique: false,
        persistent: true,
        clearOnHide: true,
        validate: {required: false, minLength: '', maxLength: '', pattern: '', custom: '', customPrivate: false},
        conditional: {show: '', when: null, eq: ''},
        type: 'textfield',
        tags: []
      }],
      type: 'panel',
      tags: [],
      conditional: {show: '', when: null, eq: ''}
    }, {
      input: true,
      label: 'Submit',
      tableView: false,
      key: 'submit',
      size: 'md',
      leftIcon: '',
      rightIcon: '',
      block: false,
      action: 'submit',
      disableOnInvalid: false,
      theme: 'primary',
      type: 'button'
    }],
    owner: '57605b5965901601001cbbd2',
    submissionAccess: [],
    access: [{
      type: 'read_all',
      roles: ['58cc056767cb9600a75712e3', '58cc056767cb9600a75712e4', '58cc056767cb9600a75712e5']
    }],
    tags: [],
    type: 'form'
  },
  tests: {
    'Test wizard control': (wizard, done) => {
      done();
    }
  }
};
