const form = {
  "_id": "5fb3a367921ccc8c3818b02a",
  "type": "form",
  "tags": [],
  "owner": "5e949fd2dfad833c8893ef44",
  "components": [{
    "label": "Data Grid",
    "labelPosition": "top",
    "description": "",
    "tooltip": "",
    "disableAddingRemovingRows": false,
    "conditionalAddButton": "",
    "reorder": false,
    "addAnother": "",
    "addAnotherPosition": "bottom",
    "defaultOpen": false,
    "layoutFixed": false,
    "enableRowGroups": false,
    "initEmpty": false,
    "customClass": "",
    "tabindex": "",
    "hidden": false,
    "hideLabel": false,
    "autofocus": false,
    "disabled": false,
    "tableView": false,
    "modalEdit": false,
    "defaultValue": [{}],
    "persistent": true,
    "protected": false,
    "dbIndex": false,
    "encrypted": false,
    "redrawOn": "",
    "clearOnHide": true,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "allowCalculateOverride": false,
    "validateOn": "change",
    "validate": {
      "required": false,
      "minLength": "",
      "maxLength": "",
      "customMessage": "",
      "custom": "",
      "customPrivate": false,
      "json": "",
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "unique": false,
    "errorLabel": "",
    "key": "dataGrid",
    "tags": [],
    "properties": {},
    "conditional": {
      "show": null,
      "when": null,
      "eq": "",
      "json": ""
    },
    "customConditional": "",
    "logic": [],
    "attributes": {},
    "overlay": {
      "style": "",
      "page": "",
      "left": "",
      "top": "",
      "width": "",
      "height": ""
    },
    "type": "datagrid",
    "input": true,
    "placeholder": "",
    "prefix": "",
    "suffix": "",
    "multiple": false,
    "refreshOn": "",
    "widget": null,
    "showCharCount": false,
    "showWordCount": false,
    "allowMultipleMasks": false,
    "tree": true,
    "components": [{
      "label": "Number",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "delimiter": false,
      "requireDecimal": false,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "min": "",
        "max": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "step": "any",
        "integer": ""
      },
      "errorLabel": "",
      "key": "number",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "number",
      "input": true,
      "unique": false,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "ep0otn0",
      "defaultValue": null
    }],
    "id": "egnjdp"
  }, {
    "type": "button",
    "label": "Submit",
    "key": "submit",
    "disableOnInvalid": true,
    "input": true,
    "tableView": false,
    "placeholder": "",
    "prefix": "",
    "customClass": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "hidden": false,
    "clearOnHide": true,
    "refreshOn": "",
    "redrawOn": "",
    "modalEdit": false,
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "tooltip": "",
    "hideLabel": false,
    "tabindex": "",
    "disabled": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": {
      "type": "input"
    },
    "attributes": {},
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "conditional": {
      "show": null,
      "when": null,
      "eq": ""
    },
    "overlay": {
      "style": "",
      "left": "",
      "top": "",
      "width": "",
      "height": ""
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "properties": {},
    "allowMultipleMasks": false,
    "size": "md",
    "leftIcon": "",
    "rightIcon": "",
    "block": false,
    "action": "submit",
    "theme": "primary",
    "dataGridLabel": true,
    "id": "eattlla"
  }],
  "title": "dataGridTest",
  "display": "form",
   "name": "dataGridTest",
  "path": "datagridtest",
  "machineName": "cjksbatcpbhyfbs:dataGridTest"
};

const submission3rows = {
  data: { 
    dataGrid: [{ number: 1 }, { number: 2 }, { number: 3  }]
  }
};

const submission1row = {
  data: { 
    dataGrid: [{ number: 555 }]
  }
};

export default {
  form: form,
  submission1row: submission1row,
  submission3rows: submission3rows,
};
