export default {
    title: 'test checkbox',
    name: 'testCheckbox',
    path: 'testcheckbox',
    type: 'form',
    display: 'form',
    components: [
      {
        label: 'Checkbox 1',
        inputType: 'radio',
        tableView: true,
        defaultValue: false,
        key: 'checkbox1',
        type: 'checkbox',
        name: 'radio',
        value: 'value1',
        input: true,
        radio: false,
      },
      {
        label: 'Checkbox 2',
        inputType: 'radio',
        tableView: true,
        defaultValue: false,
        key: 'checkbox2',
        type: 'checkbox',
        name: 'radio',
        value: 'value2',
        input: true,
      },
      {
        label: 'Checkbox',
        tableView: false,
        key: 'checkbox',
        type: 'checkbox',
        input: true,
      }
    ],
    created: '2022-09-01T09:12:45.581Z',
    modified: '2022-09-05T08:51:16.048Z',
    machineName: 'uubnbosxacwjzbk:testCheckbox',
  };
