const withClearOnHide = {
    _id: '6597badd4143681594620748',
    title: 'test clear on hide',
    name: 'testClearOnHide',
    path: 'testclearonhide',
    type: 'form',
    display: 'form',
    components: [
      {
        label: 'Checkbox',
        tableView: false,
        key: 'checkbox',
        type: 'checkbox',
        input: true,
      },
      {
        label: 'Number',
        applyMaskOn: 'change',
        mask: false,
        tableView: false,
        delimiter: false,
        requireDecimal: false,
        inputFormat: 'plain',
        truncateMultipleSpaces: false,
        allowCalculateOverride: true,
        calculateValue: 'value = 111;',
        key: 'number',
        conditional: {
          show: true,
          conjunction: 'all',
          conditions: [
            {
              component: 'checkbox',
              operator: 'isEqual',
              value: true,
            },
          ],
        },
        type: 'number',
        input: true,
      },
      {
        label: 'Text Field',
        applyMaskOn: 'change',
        tableView: true,
        calculateValue: "value = 'test';",
        allowCalculateOverride: true,
        key: 'textField',
        conditional: {
          show: true,
          conjunction: 'all',
          conditions: [
            {
              component: 'checkbox',
              operator: 'isEqual',
              value: true,
            },
          ],
        },
        type: 'textfield',
        input: true,
      },
      {
        label: 'Text Area',
        applyMaskOn: 'change',
        autoExpand: false,
        tableView: true,
        calculateValue: "value = 'test value';",
        allowCalculateOverride: true,
        key: 'textArea',
        conditional: {
          show: true,
          conjunction: 'all',
          conditions: [
            {
              component: 'checkbox',
              operator: 'isEqual',
              value: true,
            },
          ],
        },
        type: 'textarea',
        input: true,
      },
      {
        label: 'Radio',
        optionsLabelPosition: 'right',
        inline: false,
        tableView: false,
        values: [
          {
            label: 'a',
            value: 'a',
            shortcut: '',
          },
          {
            label: 'b',
            value: 'b',
            shortcut: '',
          },
          {
            label: 'c',
            value: 'c',
            shortcut: '',
          },
        ],
        calculateValue: "value = 'a';\n\n",
        allowCalculateOverride: true,
        key: 'radio',
        conditional: {
          show: true,
          conjunction: 'all',
          conditions: [
            {
              component: 'checkbox',
              operator: 'isEqual',
              value: true,
            },
          ],
        },
        type: 'radio',
        input: true,
      },
      {
        label: 'reset',
        action: 'reset',
        showValidations: false,
        tableView: false,
        key: 'reset',
        type: 'button',
        input: true,
      },
    ],
  };
  
  const withDataGrid = {
    _id: '6597baa341436815946204d1',
    title: 'test clear datagrid first raw',
    name: 'testClearDatagridFirstRaw',
    path: 'testcleardatagridfirstraw',
    type: 'form',
    display: 'form',
    components: [
      {
        label: 'Data Grid',
        reorder: false,
        addAnotherPosition: 'bottom',
        layoutFixed: false,
        enableRowGroups: false,
        initEmpty: false,
        tableView: false,
        defaultValue: [
          {
            dgRadio: '',
            textField: '',
            textArea: '',
          },
        ],
        key: 'dataGrid',
        type: 'datagrid',
        defaultOpen: false,
        alwaysEnabled: false,
        input: true,
        components: [
          {
            label: 'DG radio',
            optionsLabelPosition: 'right',
            inline: false,
            alwaysEnabled: false,
            tableView: false,
            values: [
              {
                label: 'A',
                value: 'a',
                shortcut: '',
              },
              {
                label: 'B',
                value: 'b',
                shortcut: '',
              },
              {
                label: 'C',
                value: 'c',
                shortcut: '',
              },
            ],
            allowCalculateOverride: true,
            key: 'dgRadio',
            type: 'radio',
            input: true,
          },
          {
            label: 'Text Field',
            applyMaskOn: 'change',
            tableView: true,
            calculateValue: "if (row.dgRadio == 'a'){value = 'test DataGrid'}",
            allowCalculateOverride: true,
            key: 'textField',
            type: 'textfield',
            alwaysEnabled: false,
            input: true,
          },
          {
            label: 'Number',
            applyMaskOn: 'change',
            mask: false,
            tableView: false,
            delimiter: false,
            requireDecimal: false,
            inputFormat: 'plain',
            truncateMultipleSpaces: false,
            calculateValue: 'value = 11111;',
            allowCalculateOverride: true,
            key: 'number',
            type: 'number',
            input: true,
          },
          {
            label: 'Text Area',
            applyMaskOn: 'change',
            autoExpand: false,
            tableView: true,
            calculateValue: "value = 'test';",
            allowCalculateOverride: true,
            key: 'textArea',
            type: 'textarea',
            input: true,
          },
        ],
        path: 'dataGrid',
      },
    ],
  };
  
  const withResetBtn = {
    _id: '6597c00b4143681594622563',
    title: 'recalculate on reset',
    name: 'recalculateOnReset',
    path: 'recalculateonreset',
    type: 'form',
    display: 'form',
    components: [
      {
        label: 'Data Grid',
        reorder: false,
        addAnotherPosition: 'bottom',
        layoutFixed: false,
        enableRowGroups: false,
        initEmpty: false,
        tableView: false,
        defaultValue: [
          {
            dgRadio: '',
            textField: '',
            textArea: '',
          },
        ],
        key: 'dataGrid',
        type: 'datagrid',
        defaultOpen: false,
        alwaysEnabled: false,
        input: true,
        components: [
          {
            label: 'DG radio',
            optionsLabelPosition: 'right',
            inline: false,
            alwaysEnabled: false,
            tableView: false,
            values: [
              {
                label: 'A',
                value: 'a',
                shortcut: '',
              },
              {
                label: 'B',
                value: 'b',
                shortcut: '',
              },
              {
                label: 'C',
                value: 'c',
                shortcut: '',
              },
            ],
            allowCalculateOverride: true,
            key: 'dgRadio',
            type: 'radio',
            input: true,
          },
          {
            label: 'Text Field',
            applyMaskOn: 'change',
            tableView: true,
            calculateValue: "if (row.dgRadio == 'a'){value = 'test DataGrid'}",
            allowCalculateOverride: true,
            key: 'textField',
            type: 'textfield',
            alwaysEnabled: false,
            input: true,
          },
        ],
        path: 'dataGrid',
      },
      {
        label: 'Checkbox',
        tableView: false,
        key: 'checkbox',
        type: 'checkbox',
        input: true,
      },
      {
        label: 'Radio',
        optionsLabelPosition: 'right',
        inline: false,
        tableView: false,
        values: [
          {
            label: 'one',
            value: 'one',
            shortcut: '',
          },
          {
            label: 'two',
            value: 'two',
            shortcut: '',
          },
        ],
        calculateValue: "if (data.checkbox) {\n  value = 'one';\n}",
        allowCalculateOverride: true,
        key: 'radio',
        type: 'radio',
        input: true,
      },
      {
        label: 'Text Area',
        applyMaskOn: 'change',
        autoExpand: false,
        tableView: true,
        calculateValue: "value = 'test';",
        allowCalculateOverride: true,
        key: 'textArea',
        type: 'textarea',
        input: true,
      },
      {
        label: 'Number',
        applyMaskOn: 'change',
        mask: false,
        tableView: false,
        delimiter: false,
        requireDecimal: false,
        inputFormat: 'plain',
        truncateMultipleSpaces: false,
        calculateValue: 'value = 11111;',
        allowCalculateOverride: true,
        key: 'number',
        type: 'number',
        input: true,
      },
      {
        label: 'reset',
        action: 'reset',
        showValidations: false,
        tableView: false,
        key: 'reset',
        type: 'button',
        input: true,
      },
    ],
  };
  
  const wizard = {
    _id: '65966189ac3dff73a7234dd9',
    title: 'clear rows',
    name: 'clearRows',
    path: 'clearrows',
    type: 'form',
    display: 'wizard',
    components: [
      {
        title: 'Page 1',
        label: 'Page 1',
        type: 'panel',
        key: 'page1',
        components: [
          {
            label: 'Radio',
            optionsLabelPosition: 'right',
            inline: false,
            tableView: true,
            values: [
              {
                label: ' a',
                value: 'a',
                shortcut: '',
              },
              {
                label: 'b',
                value: 'b',
                shortcut: '',
              },
              {
                label: 'c',
                value: 'c',
                shortcut: '',
              },
            ],
            allowCalculateOverride: true,
            key: 'radio1',
            type: 'radio',
            alwaysEnabled: false,
            input: true,
          },
          {
            label: 'Text Field',
            alwaysEnabled: false,
            tableView: true,
            calculateValue: "if (data.radio1 == 'a'){value = 'test data'}",
            allowCalculateOverride: true,
            key: 'textField',
            type: 'textfield',
            input: true,
          },
          {
            label: 'Text Area',
            autoExpand: false,
            alwaysEnabled: false,
            tableView: true,
            calculateValue: "if (data.radio1 == 'a'){value = 'test data'}",
            allowCalculateOverride: true,
            key: 'textArea',
            type: 'textarea',
            input: true,
          },
          {
            label: 'Number',
            mask: false,
            alwaysEnabled: false,
            tableView: false,
            delimiter: false,
            requireDecimal: false,
            inputFormat: 'plain',
            calculateValue: "if (data.radio1 == 'a'){value = 123}",
            allowCalculateOverride: true,
            key: 'number',
            type: 'number',
            input: true,
          },
          {
            label: 'Radio',
            optionsLabelPosition: 'right',
            inline: false,
            tableView: false,
            values: [
              {
                label: 'one',
                value: 'one',
                shortcut: '',
              },
              {
                label: 'two',
                value: 'two',
                shortcut: '',
              },
            ],
            calculateValue: "value = 'one'",
            allowCalculateOverride: true,
            key: 'radio',
            type: 'radio',
            input: true,
          },
        ],
        input: false,
        tableView: false,
        alwaysEnabled: false,
        path: 'page1',
      },
    ],
  };
  
  export default {
    withClearOnHide,
    withDataGrid,
    withResetBtn,
    wizard,
  };

  