export default {
  serverErrors: [
    {
      message: "Text Field - Unique must be unique",
      level: "error",
      path: ["containerNotUnique", "textFieldUnique"],
      context: {
        validator: "unique",
        hasLabel: true,
        key: "textFieldUnique",
        label: "Text Field - Unique",
        path: "containerNotUnique.textFieldUnique",
        value: "1",
        index: 0,
      },
      fromServer: true,
    },
    {
      message: "Text Field must be unique",
      level: "error",
      path: ["dataGrid", 0, "textField"],
      context: {
        validator: "unique",
        hasLabel: true,
        key: "textField",
        label: "Text Field",
        path: "dataGrid[0].textField",
        value: "1",
        index: 0,
      },
      fromServer: true,
    },
  ],
  values: {
    data: {
      containerNotUnique: { textFieldUnique: "1" },
      dataGrid: [{ textField: "1" }],
      submit: true,
    },
  },
  form: {
    _id: "6852bffb1e68937544ee1027",
    title: "container",
    name: "container",
    path: "container",
    type: "form",
    display: "form",
    components: [
      {
        label: "Container - not Unique",
        hideLabel: false,
        tableView: false,
        validateWhenHidden: false,
        key: "containerNotUnique",
        type: "container",
        input: true,
        components: [
          {
            label: "Text Field - Unique",
            applyMaskOn: "change",
            tableView: true,
            unique: true,
            validateWhenHidden: false,
            key: "textFieldUnique",
            type: "textfield",
            input: true,
          },
          {
            label: "Number",
            applyMaskOn: "change",
            mask: false,
            tableView: false,
            delimiter: false,
            requireDecimal: false,
            inputFormat: "plain",
            truncateMultipleSpaces: false,
            validateWhenHidden: false,
            key: "number",
            type: "number",
            input: true,
          },
        ],
      },
      {
        label: "Data Grid",
        reorder: false,
        addAnotherPosition: "bottom",
        layoutFixed: false,
        enableRowGroups: false,
        initEmpty: false,
        tableView: false,
        defaultValue: [{}],
        validateWhenHidden: false,
        key: "dataGrid",
        type: "datagrid",
        input: true,
        components: [
          {
            label: "Text Field",
            applyMaskOn: "change",
            tableView: true,
            unique: true,
            validateWhenHidden: false,
            key: "textField",
            type: "textfield",
            input: true,
          },
        ],
      },
      {
        label: "Submit",
        tableView: false,
        key: "submit",
        type: "button",
        input: true,
        saveOnEnter: false,
      },
    ],
    machineName: "authoring-urmcnpgrgmhvrez:container",
    project: "6852a08f5bd31ff78970ed70",
    created: "2025-06-18T13:32:43.503Z",
    modified: "2025-06-19T09:44:20.605Z",
  },
};
