export default {
  _id: '69108caee31ff25d6d36b506',
  title: 'parent 1',
  name: 'parent1',
  path: 'parent1',
  type: 'form',
  display: 'form',
  components: [
    {
      label: 'Text Field parent',
      applyMaskOn: 'change',
      tableView: true,
      validateWhenHidden: false,
      key: 'textFieldParent',
      type: 'textfield',
      input: true,
    },
    {
      label: 'Form',
      hidden: true,
      tableView: true,
      form: '69108caee31ff25d6d36b4ff',
      useOriginalRevision: false,
      clearOnHide: true,
      key: 'form',
      type: 'form',
      input: true,
      components: [
        {
          label: 'Text Field 2 child',
          applyMaskOn: 'change',
          tableView: true,
          validate: {
            required: true,
            custom: '',
            customPrivate: false,
            strictDateValidation: false,
            multiple: false,
            unique: false,
            minLength: '',
            maxLength: '',
            pattern: '',
          },
          validateWhenHidden: false,
          key: 'textField2Child',
          type: 'textfield',
          input: true,
          id: 'eblr8t9',
          placeholder: '',
          prefix: '',
          customClass: '',
          suffix: '',
          multiple: false,
          defaultValue: null,
          protected: false,
          unique: false,
          persistent: true,
          hidden: false,
          clearOnHide: true,
          refreshOn: '',
          redrawOn: '',
          modalEdit: false,
          dataGridLabel: false,
          labelPosition: 'top',
          description: '',
          errorLabel: '',
          tooltip: '',
          hideLabel: false,
          tabindex: '',
          disabled: false,
          autofocus: false,
          dbIndex: false,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          widget: {
            type: 'input',
          },
          attributes: {},
          validateOn: 'change',
          conditional: {
            show: null,
            when: null,
            eq: '',
          },
          overlay: {
            style: '',
            left: '',
            top: '',
            width: '',
            height: '',
          },
          allowCalculateOverride: false,
          encrypted: false,
          showCharCount: false,
          showWordCount: false,
          properties: {},
          allowMultipleMasks: false,
          addons: [],
          mask: false,
          inputType: 'text',
          inputFormat: 'plain',
          inputMask: '',
          displayMask: '',
          spellcheck: true,
          truncateMultipleSpaces: false,
        },
        {
          type: 'button',
          label: 'Submit',
          key: 'submit',
          disableOnInvalid: true,
          input: true,
          tableView: false,
          hidden: true,
          customConditional: 'show = false',
          id: 'exfh9n',
          placeholder: '',
          prefix: '',
          customClass: '',
          suffix: '',
          multiple: false,
          defaultValue: null,
          protected: false,
          unique: false,
          persistent: false,
          clearOnHide: true,
          refreshOn: '',
          redrawOn: '',
          modalEdit: false,
          dataGridLabel: true,
          labelPosition: 'top',
          description: '',
          errorLabel: '',
          tooltip: '',
          hideLabel: false,
          tabindex: '',
          disabled: false,
          autofocus: false,
          dbIndex: false,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          widget: {
            type: 'input',
          },
          attributes: {},
          validateOn: 'change',
          validate: {
            required: false,
            custom: '',
            customPrivate: false,
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          conditional: {
            show: null,
            when: null,
            eq: '',
          },
          overlay: {
            style: '',
            left: '',
            top: '',
            width: '',
            height: '',
          },
          allowCalculateOverride: false,
          encrypted: false,
          showCharCount: false,
          showWordCount: false,
          properties: {},
          allowMultipleMasks: false,
          addons: [],
          size: 'md',
          leftIcon: '',
          rightIcon: '',
          block: false,
          action: 'submit',
          theme: 'primary',
        },
      ],
      display: 'form',
      keyModified: true,
    },
    {
      label: 'Submit',
      tableView: false,
      key: 'submit',
      type: 'button',
      input: true,
      saveOnEnter: false,
    },
  ],
  pdfComponents: [],
  settings: {},
  properties: {},
  machineName: 'zjmpfnhcmfewehb:parent1',
  project: '68f206eb77804fe4f4d850ea',
  controller: '',
  revisions: '',
  submissionRevisions: '',
  _vid: 0,
  esign: {},
  created: '2025-11-09T12:44:30.049Z',
  modified: '2025-11-09T13:21:35.226Z',
};
