const parentWizard = {
  _id: '671218f1f2a193e287605944',
  title: 'Wizard with Child Wizard failing validation cannot be linked to',
  name: 'wizardWithChildWizardFailingValidationCannotBeLinkedTo',
  path: 'wizardwithchildwizardfailingvalidationcannotbelinkedto',
  type: 'form',
  display: 'wizard',
  owner: '671225d7f2a193e287607cec',
  components: [
    {
      title: 'Page 1',
      breadcrumbClickable: true,
      buttonSettings: {
        previous: true,
        cancel: false,
        next: true,
      },
      navigateOnEnter: false,
      saveOnEnter: false,
      scrollToTop: false,
      collapsible: false,
      key: 'page1',
      type: 'panel',
      label: 'Page 1',
      components: [
        {
          label: 'Text Field',
          applyMaskOn: 'change',
          tableView: true,
          validate: {
            required: true,
          },
          key: 'textField',
          type: 'textfield',
          input: true,
        },
      ],
      input: false,
      tableView: false,
    },
    {
      title: 'Page 2',
      breadcrumbClickable: true,
      buttonSettings: {
        previous: true,
        cancel: true,
        next: true,
      },
      navigateOnEnter: false,
      saveOnEnter: false,
      scrollToTop: false,
      collapsible: false,
      key: 'page2',
      type: 'panel',
      label: 'Page 2',
      components: [
        {
          label: 'Number',
          applyMaskOn: 'change',
          mask: false,
          tableView: false,
          delimiter: false,
          requireDecimal: false,
          inputFormat: 'plain',
          truncateMultipleSpaces: false,
          key: 'number',
          type: 'number',
          input: true,
        },
      ],
      input: false,
      tableView: false,
    },
    {
      title: 'Page 3',
      breadcrumbClickable: true,
      buttonSettings: {
        previous: true,
        cancel: true,
        next: true,
      },
      navigateOnEnter: false,
      saveOnEnter: false,
      scrollToTop: false,
      collapsible: false,
      key: 'page3',
      type: 'panel',
      label: 'Page 3',
      input: false,
      tableView: false,
      components: [
        {
          label: 'Child',
          tableView: true,
          form: '671218f1f2a193e28760593d',
          useOriginalRevision: false,
          key: 'child',
          type: 'form',
          input: true,
        },
      ],
    },
  ],
  pdfComponents: [],
  settings: {},
  project: '66f26afae0c7ef9920ae596d',
  created: '2024-10-18T08:14:41.116Z',
  modified: '2024-10-18T09:31:29.298Z',
};

const childWizard = {
  _id: '671218f1f2a193e28760593d',
  title: 'Wizard child with required field',
  name: 'wizardChildWithRequiredField',
  path: 'wizardchildwithrequiredfield',
  type: 'form',
  display: 'wizard',
  owner: '67122610f2a193e287607e58',
  components: [
    {
      title: 'Page 1',
      label: 'Page 1',
      type: 'panel',
      key: 'page1',
      components: [
        {
          label: 'Text Field child',
          applyMaskOn: 'change',
          tableView: true,
          validateWhenHidden: false,
          key: 'textField',
          type: 'textfield',
          input: true,
          id: 'ews598d',
          placeholder: '',
          prefix: '',
          customClass: '',
          suffix: '',
          multiple: false,
          defaultValue: null,
          protected: false,
          unique: false,
          persistent: true,
          hidden: false,
          clearOnHide: true,
          refreshOn: '',
          redrawOn: '',
          modalEdit: false,
          dataGridLabel: false,
          labelPosition: 'top',
          description: '',
          errorLabel: '',
          tooltip: '',
          hideLabel: false,
          tabindex: '',
          disabled: false,
          autofocus: false,
          dbIndex: false,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          widget: {
            type: 'input',
          },
          attributes: {},
          validateOn: 'change',
          validate: {
            required: false,
            custom: '',
            customPrivate: false,
            strictDateValidation: false,
            multiple: false,
            unique: false,
            minLength: '',
            maxLength: '',
            pattern: '',
          },
          conditional: {
            show: null,
            when: null,
            eq: '',
          },
          overlay: {
            style: '',
            left: '',
            top: '',
            width: '',
            height: '',
          },
          allowCalculateOverride: false,
          encrypted: false,
          showCharCount: false,
          showWordCount: false,
          properties: {},
          allowMultipleMasks: false,
          addons: [],
          mask: false,
          inputType: 'text',
          inputFormat: 'plain',
          inputMask: '',
          displayMask: '',
          spellcheck: true,
          truncateMultipleSpaces: false,
        },
      ],
      input: false,
      tableView: false,
      id: 'emsfd4n',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: false,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: null,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      conditional: {
        show: null,
        when: null,
        eq: '',
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
      tree: false,
      lazyLoad: false,
      theme: 'default',
      breadcrumb: 'default',
    },
    {
      title: 'Page 2',
      label: 'Page 2',
      type: 'panel',
      key: 'page2',
      components: [
        {
          label: 'Text Field2 child',
          applyMaskOn: 'change',
          tableView: true,
          validate: {
            required: true,
            custom: '',
            customPrivate: false,
            strictDateValidation: false,
            multiple: false,
            unique: false,
            minLength: '',
            maxLength: '',
            pattern: '',
          },
          validateWhenHidden: false,
          key: 'textField2Child',
          type: 'textfield',
          input: true,
          id: 'ezycu4u',
          placeholder: '',
          prefix: '',
          customClass: '',
          suffix: '',
          multiple: false,
          defaultValue: null,
          protected: false,
          unique: false,
          persistent: true,
          hidden: false,
          clearOnHide: true,
          refreshOn: '',
          redrawOn: '',
          modalEdit: false,
          dataGridLabel: false,
          labelPosition: 'top',
          description: '',
          errorLabel: '',
          tooltip: '',
          hideLabel: false,
          tabindex: '',
          disabled: false,
          autofocus: false,
          dbIndex: false,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          widget: {
            type: 'input',
          },
          attributes: {},
          validateOn: 'change',
          conditional: {
            show: null,
            when: null,
            eq: '',
          },
          overlay: {
            style: '',
            left: '',
            top: '',
            width: '',
            height: '',
          },
          allowCalculateOverride: false,
          encrypted: false,
          showCharCount: false,
          showWordCount: false,
          properties: {},
          allowMultipleMasks: false,
          addons: [],
          mask: false,
          inputType: 'text',
          inputFormat: 'plain',
          inputMask: '',
          displayMask: '',
          spellcheck: true,
          truncateMultipleSpaces: false,
        },
      ],
      input: false,
      tableView: false,
      id: 'ehk76vf',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: false,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: null,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      conditional: {
        show: null,
        when: null,
        eq: '',
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
      tree: false,
      lazyLoad: false,
      theme: 'default',
      breadcrumb: 'default',
    },
    {
      title: 'Page 3',
      label: 'Page 3',
      type: 'panel',
      key: 'page3',
      components: [
        {
          label: 'Text Field 3 child',
          labelPosition: 'top',
          placeholder: '',
          description: '',
          tooltip: '',
          prefix: '',
          suffix: '',
          widget: {
            type: 'input',
          },
          inputMask: '',
          displayMask: '',
          applyMaskOn: 'change',
          allowMultipleMasks: false,
          customClass: '',
          tabindex: '',
          autocomplete: '',
          hidden: false,
          hideLabel: false,
          showWordCount: false,
          showCharCount: false,
          mask: false,
          autofocus: false,
          spellcheck: true,
          disabled: false,
          tableView: true,
          modalEdit: false,
          multiple: false,
          persistent: true,
          inputFormat: 'plain',
          protected: false,
          dbIndex: false,
          case: '',
          truncateMultipleSpaces: false,
          encrypted: false,
          redrawOn: '',
          clearOnHide: true,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          allowCalculateOverride: false,
          validateOn: 'change',
          validate: {
            required: true,
            pattern: '',
            customMessage: '',
            custom: '',
            customPrivate: false,
            json: '',
            minLength: '',
            maxLength: '',
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          unique: false,
          validateWhenHidden: false,
          errorLabel: '',
          errors: '',
          key: 'textField3Child',
          tags: [],
          properties: {},
          conditional: {
            show: null,
            conjunction: '',
            conditions: [],
            json: '',
            when: null,
            eq: '',
          },
          customConditional: '',
          logic: [],
          attributes: {},
          overlay: {
            style: '',
            page: '',
            left: '',
            top: '',
            width: '',
            height: '',
          },
          type: 'textfield',
          dataGridLabel: false,
          input: true,
          refreshOn: '',
          addons: [],
          inputType: 'text',
          id: 'emz75co',
          defaultValue: '',
        },
      ],
      id: 'enn4a7',
      input: false,
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: false,
      refreshOn: '',
      redrawOn: '',
      tableView: false,
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: null,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      conditional: {
        show: null,
        when: null,
        eq: '',
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
      tree: false,
      lazyLoad: false,
      theme: 'default',
      breadcrumb: 'default',
    },
  ],
  project: '66f26afae0c7ef9920ae596d',
  created: '2024-10-18T08:14:41.092Z',
  modified: '2024-10-18T12:12:55.062Z',
};

export default { parentWizard, childWizard };
