export default {
  mainForm: {
    _id: '6811ed8780ba48135398e34e',
    title: 'eSubmissionsExt',
    name: 'eSubmissionsExt',
    path: 'esubmissionsext',
    type: 'form',
    display: 'wizard',
    owner: '6811edaa80ba48135398e899',
    components: [
      {
        title: 'eSubmissions',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'eSubmissions',
        type: 'panel',
        label: 'Page 1',
        components: [
          {
            label: 'Text Field',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textField',
            type: 'textfield',
            input: true,
          },
          {
            label: 'PMTA',
            tableView: true,
            form: '6811ed8780ba48135398e347',
            useOriginalRevision: false,
            key: 'pmta',
            conditional: {
              show: true,
              conjunction: 'all',
              conditions: [
                {
                  component: 'textField',
                  operator: 'isEqual',
                  value: '5',
                },
              ],
            },
            type: 'form',
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
    ],
    machineName: 'authoring-lszihwhpgvtoncg:eSubmissionsExt',
    project: '6811ed7a80ba48135398e015',
  },
  '6811ed8780ba48135398e347': {
    _id: '6811ed8780ba48135398e347',
    title: 'PMTA',
    name: 'pmta',
    path: 'pmta',
    type: 'form',
    display: 'wizard',
    owner: '6811edb780ba48135398e9c6',
    components: [
      {
        title: 'Section I - Applicant Identification',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'section1',
        properties: {
          hideQc: 'true',
        },
        type: 'panel',
        label: 'Page 6',
        input: false,
        tableView: false,
        components: [
          {
            label: 'Identification Information',
            tableView: true,
            form: '6811ed8680ba48135398e340',
            useOriginalRevision: false,
            reference: false,
            clearOnHide: false,
            key: 'contacts',
            type: 'form',
            input: true,
          },
        ],
      },
    ],
    machineName: 'authoring-lszihwhpgvtoncg:pmta',
    project: '6811ed7a80ba48135398e015',
    created: '2025-04-30T09:29:43.003Z',
    modified: '2025-05-05T10:32:00.688Z',
  },
  '6811ed8680ba48135398e340': {
    _id: '6811ed8680ba48135398e340',
    title: 'PMTA Identification Information',
    name: 'pmtaIdentificationInformation',
    path: 'pmtaidentificationinformation',
    type: 'form',
    display: 'wizard',
    owner: '6811edc280ba48135398eaf2',
    components: [
      {
        title: 'Part A: Applicant Identification',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'section1A',
        properties: {
          subsection: '1',
        },
        type: 'panel',
        label: 'Page 1',
        components: [
          {
            label: 'Applicant Organization',
            tableView: true,
            form: '6811ed8680ba48135398e32b',
            useOriginalRevision: false,
            reference: false,
            clearOnHide: false,
            key: 'applicantOrganization',
            type: 'form',
            lazyLoad: true,
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
      {
        title: 'Part B: Authorized Representative or U.S. Agent Information',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'section1B',
        properties: {
          subsection: '1',
        },
        type: 'panel',
        label: 'Page 1',
        components: [
          {
            label: 'Authorized Representative',
            tableView: true,
            form: '6811ed8680ba48135398e339',
            useOriginalRevision: false,
            reference: false,
            clearOnHide: false,
            key: 'authorizedRepresentative',
            type: 'form',
            lazyLoad: true,
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
    ],
    machineName: 'authoring-lszihwhpgvtoncg:pmtaIdentificationInformation',
    project: '6811ed7a80ba48135398e015',
    created: '2025-04-30T09:29:42.994Z',
    modified: '2025-05-05T10:31:54.188Z',
  },
  '6811ed8680ba48135398e32b': {
    _id: '6811ed8680ba48135398e32b',
    title: 'Generic Applicant Organization',
    name: 'genericApplicantOrganization',
    path: 'genericapplicantorganization',
    type: 'form',
    display: 'form',
    tags: ['Generic'],
    access: [
      {
        type: 'create_own',
        roles: [],
      },
      {
        type: 'create_all',
        roles: [],
      },
      {
        type: 'read_own',
        roles: [],
      },
      {
        type: 'read_all',
        roles: ['000000000000000000000000'],
      },
      {
        type: 'update_own',
        roles: [],
      },
      {
        type: 'update_all',
        roles: [],
      },
      {
        type: 'delete_own',
        roles: [],
      },
      {
        type: 'delete_all',
        roles: [],
      },
      {
        type: 'team_read',
        roles: [],
      },
      {
        type: 'team_write',
        roles: [],
      },
      {
        type: 'team_admin',
        roles: [],
      },
    ],
    submissionAccess: [
      {
        type: 'create_own',
        roles: [],
      },
      {
        type: 'create_all',
        roles: [],
      },
      {
        type: 'read_own',
        roles: [],
      },
      {
        type: 'read_all',
        roles: [],
      },
      {
        type: 'update_own',
        roles: [],
      },
      {
        type: 'update_all',
        roles: [],
      },
      {
        type: 'delete_own',
        roles: [],
      },
      {
        type: 'delete_all',
        roles: [],
      },
      {
        type: 'team_read',
        roles: [],
      },
      {
        type: 'team_write',
        roles: [],
      },
      {
        type: 'team_admin',
        roles: [],
      },
    ],
    owner: '6811edea80ba48135398ee78',
    components: [
      {
        label: 'Text Field',
        applyMaskOn: 'change',
        tableView: true,
        validateWhenHidden: false,
        key: 'textField',
        type: 'textfield',
        input: true,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    pdfComponents: [],
    settings: {},
    properties: {},
    machineName: 'authoring-lszihwhpgvtoncg:genericApplicantOrganization',
    project: '6811ed7a80ba48135398e015',
    controller: '',
    revisions: '',
    submissionRevisions: '',
    _vid: 0,
    esign: {},
    created: '2025-04-30T09:29:42.961Z',
    modified: '2025-05-05T10:35:31.411Z',
    fieldMatchAccess: {
      read: [
        {
          formFieldPath: '',
          value: '',
          operator: '$eq',
          valueType: 'string',
          roles: [],
        },
      ],
      write: [
        {
          formFieldPath: '',
          value: '',
          operator: '$eq',
          valueType: 'string',
          roles: [],
        },
      ],
      create: [
        {
          formFieldPath: '',
          value: '',
          operator: '$eq',
          valueType: 'string',
          roles: [],
        },
      ],
      admin: [
        {
          formFieldPath: '',
          value: '',
          operator: '$eq',
          valueType: 'string',
          roles: [],
        },
      ],
      delete: [
        {
          formFieldPath: '',
          value: '',
          operator: '$eq',
          valueType: 'string',
          roles: [],
        },
      ],
      update: [
        {
          formFieldPath: '',
          value: '',
          operator: '$eq',
          valueType: 'string',
          roles: [],
        },
      ],
      _id: '6811edea80ba48135398ee77',
    },
  },
  '6811ed8680ba48135398e339': {
    _id: '6811ed8680ba48135398e339',
    title: 'Generic Authorized Representative',
    name: 'genericAuthorizedRepresentative',
    path: 'genericauthorizedrepresentative',
    type: 'form',
    display: 'form',
    owner: '6811edce80ba48135398ec1e',
    components: [
      {
        label: 'Organization',
        tableView: true,
        form: '6811ed8680ba48135398e332',
        useOriginalRevision: false,
        reference: false,
        key: 'organization',
        type: 'form',
        input: true,
        clearOnHide: false,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    machineName: 'authoring-lszihwhpgvtoncg:genericAuthorizedRepresentative',
    project: '6811ed7a80ba48135398e015',
    created: '2025-04-30T09:29:42.983Z',
    modified: '2025-04-30T09:30:54.656Z',
  },
  '6811ed8680ba48135398e332': {
    _id: '6811ed8680ba48135398e332',
    title: 'Generic Organization',
    name: 'genericOrganization',
    path: 'genericorganization',
    type: 'form',
    display: 'form',
    owner: '6811edde80ba48135398ed4b',
    components: [
      {
        label: 'Organization Name',
        applyMaskOn: 'change',
        tableView: true,
        clearOnHide: false,
        validate: {
          maxLength: 100,
        },
        validateWhenHidden: false,
        key: 'organizationName',
        type: 'textfield',
        input: true,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    machineName: 'authoring-lszihwhpgvtoncg:genericOrganization',
    project: '6811ed7a80ba48135398e015',
    created: '2025-04-30T09:29:42.971Z',
    modified: '2025-04-30T09:42:20.376Z',
  },
};
