export default {
  wizard: {
    _id: '689f3451fe27f634ffeba380',
    title: 'wizard parent',
    name: 'wizardParent',
    path: 'wizardparent',
    type: 'form',
    display: 'wizard',
    owner: '689f3c89fe27f634ffebb343',
    components: [
      {
        title: 'Page 1',
        label: 'Page 1',
        type: 'panel',
        key: 'page1',
        components: [
          {
            label: 'Text Field',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textField',
            type: 'textfield',
            input: true,
            defaultValue: 'External',
          },
        ],
        input: false,
        tableView: false,
      },
      {
        title: 'Page 2',
        label: 'Page 2',
        type: 'panel',
        key: 'page2',
        components: [
          {
            label: 'Form',
            tableView: true,
            form: '689f3451fe27f634ffeba379',
            useOriginalRevision: false,
            key: 'form',
            type: 'form',
            lazyLoad: true,
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
      {
        title: 'Page 3',
        label: 'Page 3',
        type: 'panel',
        key: 'page3',
        components: [
          {
            label: 'Third Page',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'thirdPage',
            type: 'textfield',
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
    ],
    machineName: 'testtt-izutenexavvxnws:wizardButBetter',
    project: '689ef24afe27f634ffeb8859',
    created: '2025-08-15T13:21:21.417Z',
    modified: '2025-08-15T13:56:33.975Z',
  },
  nestedFormTop: {
    _id: '689f3451fe27f634ffeba379',
    title: 'Wizard Child Owner',
    name: 'wizardChildOwner',
    path: 'wizardchildowner',
    type: 'form',
    display: 'form',
    owner: '689f3d19fe27f634ffebb7a1',
    components: [
      {
        label: 'Form',
        tableView: true,
        form: '689f3451fe27f634ffeba372',
        useOriginalRevision: false,
        reference: false,
        key: 'form',
        type: 'form',
        input: true,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    machineName: 'testtt-izutenexavvxnws:wizardChildOwner',
    project: '689ef24afe27f634ffeb8859',
    created: '2025-08-15T13:21:21.409Z',
    modified: '2025-08-15T13:58:49.954Z',
  },
  nestedFormChild: {
    _id: '689f3451fe27f634ffeba372',
    title: 'Wizard Child',
    name: 'wizardChild',
    path: 'wizardchild',
    type: 'form',
    display: 'form',
    owner: '689f3d42fe27f634ffebb8d6',
    components: [
      {
        label: 'Text Field',
        applyMaskOn: 'change',
        tableView: true,
        validateWhenHidden: false,
        key: 'textField',
        logic: [
          {
            name: 'Set to required',
            trigger: {
              type: 'javascript',
              javascript: 'result = true;',
            },
            actions: [
              {
                name: 'Set to Required',
                type: 'property',
                property: {
                  label: 'Required',
                  value: 'validate.required',
                  type: 'boolean',
                },
                state: true,
              },
            ],
          },
        ],
        type: 'textfield',
        input: true,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    machineName: 'testtt-izutenexavvxnws:wizardChild',
    project: '689ef24afe27f634ffeb8859',
    created: '2025-08-15T13:21:21.399Z',
    modified: '2025-08-15T13:59:30.108Z',
  },
};
