export default {
  parentWizard: {
    _id: '6895e4628d9bfeaf8fe1a975',
    title: 'Wizard A',
    name: 'wizardA',
    path: 'wizarda',
    type: 'form',
    display: 'wizard',
    components: [
      {
        title: 'Wizard A Part A',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'wizardAPartA',
        type: 'panel',
        label: 'Page 1',
        input: false,
        tableView: false,
        components: [
          {
            label: 'HTML',
            attrs: [
              {
                attr: '',
                value: '',
              },
            ],
            content: '<h2><b>Wizard A Part A</b></h2>',
            refreshOnChange: false,
            key: 'html1a',
            type: 'htmlelement',
            input: false,
            tableView: false,
          },
          {
            label: 'Wizard B',
            tableView: true,
            form: '6895e4628d9bfeaf8fe1a96e',
            useOriginalRevision: false,
            reference: false,
            key: 'wizardB',
            type: 'form',
            input: true,
          },
          {
            label: 'Title',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'title',
            type: 'textfield',
            input: true,
          },
        ],
      },
    ],
    machineName: 'testsomething-oiborbwhudipbfj:wizardA',
    project: '6895e4598d9bfeaf8fe1a8b5',
  },
  nestedWizard: {
    _id: '6895e4628d9bfeaf8fe1a96e',
    title: 'Wizard B',
    name: 'wizardB',
    path: 'wizardb',
    type: 'form',
    display: 'wizard',
    components: [
      {
        label: 'Wizard B Part A',
        title: 'Wizard B Part A',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'wizardBPartA',
        type: 'panel',
        input: false,
        tableView: false,
        components: [
          {
            label: 'HTML',
            attrs: [
              {
                attr: '',
                value: '',
              },
            ],
            content: '<h2><b>Wizard B Part A</b></h2>\n<div>page apiKey is [wizardBPartA]</div>',
            refreshOnChange: false,
            key: 'html1',
            type: 'htmlelement',
            input: false,
            tableView: false,
          },
          {
            label: 'Form A or B',
            optionsLabelPosition: 'right',
            inline: false,
            tableView: false,
            values: [
              {
                label: 'A',
                value: 'a',
                shortcut: '',
              },
              {
                label: 'B',
                value: 'b',
                shortcut: '',
              },
            ],
            validateWhenHidden: false,
            key: 'formAOrB',
            type: 'radio',
            input: true,
          },
          {
            label: 'Form A',
            tableView: true,
            form: '6895e4628d9bfeaf8fe1a95f',
            useOriginalRevision: false,
            reference: false,
            key: 'formA',
            conditional: {
              show: true,
              conjunction: 'all',
              conditions: [
                {
                  component: 'formAOrB',
                  operator: 'isEqual',
                  value: 'a',
                },
              ],
            },
            type: 'form',
            input: true,
            lazyLoad: true,
          },
        ],
      },
      {
        label: 'Wizard B Part B',
        title: 'Wizard B Part B',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'wizardBPartB',
        type: 'panel',
        input: false,
        tableView: false,
        components: [
          {
            label: 'Number',
            applyMaskOn: 'change',
            mask: false,
            tableView: false,
            delimiter: false,
            requireDecimal: false,
            inputFormat: 'plain',
            truncateMultipleSpaces: false,
            validateWhenHidden: false,
            key: 'number',
            type: 'number',
            input: true,
          },
        ],
      },
    ],
    machineName: 'testsomething-oiborbwhudipbfj:wizardB',
    project: '6895e4598d9bfeaf8fe1a8b5',
  },
  nestedForm: {
    _id: '6895e4628d9bfeaf8fe1a95f',
    title: 'Wizard Base 1',
    name: 'wizardBase1',
    path: 'wizardbase1',
    type: 'form',
    display: 'form',
    owner: '6895ed9660b1378ea0e1e326',
    components: [
      {
        label: 'First Name',
        applyMaskOn: 'change',
        tableView: true,
        validate: {
          required: true,
        },
        validateWhenHidden: false,
        key: 'firstName',
        tags: [
          'recommended',
        ],
        type: 'textfield',
        input: true,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    machineName: 'testsomething-oiborbwhudipbfj:wizardBase1',
    project: '6895e4598d9bfeaf8fe1a8b5',
  },
};
