export default {
  _id: '68ac2d19ca88b30e3544e46c',
  title: 'Path example',
  name: 'pathExample',
  path: 'pathexample',
  type: 'form',
  display: 'form',
  owner: '68ac2d7fca88b30e3544e83e',
  components: [
    {
      label: 'Your contact details',
      tableView: false,
      validate: {
        required: true,
        custom:
          'if (_.isEmpty(_.get(data,`${instance.path}.phone`)) && \n_.isEmpty(_.get(data,`${instance.path}.email`))) {\n  valid=`One of either phone or email must be provided.`;\n}',
      },
      key: 'contact',
      type: 'container',
      input: true,
      components: [
        {
          label: 'HTML',
          attrs: [
            {
              attr: '',
              value: '',
            },
          ],
          content: 'utuut',
          refreshOnChange: false,
          key: 'htmloooo',
          type: 'htmlelement',
          input: false,
          tableView: false,
        },
        {
          label: 'Panel',
          collapsible: false,
          key: 'panel',
          type: 'panel',
          input: false,
          tableView: false,
          components: [
            {
              label: 'Number',
              applyMaskOn: 'change',
              mask: false,
              tableView: false,
              delimiter: false,
              requireDecimal: false,
              inputFormat: 'plain',
              truncateMultipleSpaces: false,
              validateWhenHidden: false,
              key: 'number',
              type: 'number',
              input: true,
            },
          ],
        },
        {
          label: 'Phone',
          applyMaskOn: 'change',
          tableView: true,
          key: 'phone',
          type: 'textfield',
          input: true,
        },
        {
          label: 'Email',
          applyMaskOn: 'change',
          tableView: true,
          key: 'email',
          type: 'email',
          input: true,
        },
      ],
    },
    {
      label: 'Submit',
      tableView: false,
      key: 'submit',
      type: 'button',
      input: true,
      saveOnEnter: false,
    },
  ],
  machineName: 'izutenexavvxnws:pathExample',
  project: '67211a9aa929e4e6ebc2bf77',
};
