export default {
  form: {
    _id: 'testEventsFormId',
    title: 'test form events',
    name: 'testFormEvents',
    path: 'testformevents',
    type: 'form',
    display: 'form',
    components: [
      {
        label: 'Upload',
        tableView: false,
        storage: 'base64',
        webcam: false,
        capture: false,
        fileTypes: [
          {
            label: '',
            value: '',
          },
        ],
        validateWhenHidden: false,
        key: 'file',
        type: 'file',
        input: true,
      },
      {
        label: 'Edit Grid',
        tableView: false,
        validateWhenHidden: false,
        rowDrafts: false,
        key: 'editGrid',
        type: 'editgrid',
        displayAsTable: false,
        input: true,
        components: [
          {
            label: 'Text Field in edit grid',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textFieldInEditGrid',
            type: 'textfield',
            input: true,
          },
        ],
      },
      {
        label: 'Edit Grid Modal Row',
        tableView: false,
        modal: true,
        validateWhenHidden: false,
        rowDrafts: false,
        key: 'editGridModalRow',
        type: 'editgrid',
        displayAsTable: false,
        input: true,
        components: [
          {
            label: 'Text Field in edit grid',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textFieldInEditGrid',
            type: 'textfield',
            input: true,
          },
        ],
      },
      {
        label: 'Text Field',
        applyMaskOn: 'change',
        tableView: true,
        validateWhenHidden: false,
        key: 'textField',
        type: 'textfield',
        input: true,
      },
      {
        label: 'Number',
        applyMaskOn: 'change',
        mask: false,
        tableView: false,
        delimiter: false,
        requireDecimal: false,
        inputFormat: 'plain',
        truncateMultipleSpaces: false,
        validate: {
          min: 10,
          max: 100,
        },
        validateWhenHidden: false,
        key: 'number',
        type: 'number',
        input: true,
      },
      {
        label: 'Checkbox',
        tableView: false,
        validateWhenHidden: false,
        key: 'checkbox',
        conditional: {
          show: true,
          conjunction: 'all',
          conditions: [
            {
              component: 'textField',
              operator: 'isEqual',
              value: 'show',
            },
          ],
        },
        type: 'checkbox',
        input: true,
        defaultValue: false,
      },
      {
        label: 'Delete Submission',
        action: 'delete',
        tableView: false,
        key: 'deleteSubmission',
        type: 'button',
        input: true,
        showValidations: false,
      },
      {
        label: 'Custom event',
        action: 'event',
        tableView: false,
        key: 'customEvent',
        type: 'button',
        input: true,
        showValidations: false,
        event: 'testCustomEvent',
      },
      {
        label: 'Custom url',
        action: 'url',
        tableView: false,
        key: 'customUrl',
        type: 'button',
        input: true,
        showValidations: false,
        url: 'https://www.test.com',
        headers: [
          {
            header: '',
            value: '',
          },
        ],
      },
      {
        label: 'Submit',
        tableView: false,
        key: 'submit',
        type: 'button',
        input: true,
        saveOnEnter: false,
      },
    ],
    project: '6929620d3e9176a6e367a50d',
    machineName: 'aadhfmemgjchvec:testFormEvents',
  },
  wizard: {
    _id: '6964d24d7981c9efc732f679',
    title: 'test wizard events',
    name: 'testWizardEvents',
    path: 'testwizardevents',
    type: 'form',
    display: 'wizard',
    components: [
      {
        title: 'Page 1',
        label: 'Page 1',
        type: 'panel',
        key: 'page1',
        components: [
          {
            label: 'Text Field',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textField',
            type: 'textfield',
            input: true,
            'widget.type': 'input',
          },
        ],
        input: false,
        tableView: false,
      },
      {
        title: 'Page 2',
        label: 'Page 2',
        type: 'panel',
        key: 'page2',
        components: [
          {
            label: 'Number',
            applyMaskOn: 'change',
            mask: false,
            tableView: false,
            delimiter: false,
            requireDecimal: false,
            inputFormat: 'plain',
            truncateMultipleSpaces: false,
            validateWhenHidden: false,
            key: 'number',
            type: 'number',
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
      {
        title: 'Page 3',
        label: 'Page 3',
        type: 'panel',
        key: 'page3',
        components: [
          {
            label: 'Text Area',
            applyMaskOn: 'change',
            autoExpand: false,
            tableView: true,
            validateWhenHidden: false,
            key: 'textArea',
            type: 'textarea',
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
    ],
    project: '6929620d3e9176a6e367a50d',
    created: '2026-01-12T10:51:57.695Z',
    modified: '2026-01-12T10:51:57.711Z',
    machineName: 'aadhfmemgjchvec:testWizardEvents',
  },
};
