export default {
  _id: '66f2b0e234ac6c4049cbc83c',
  title: 'test json datatype',
  name: 'testJsonDatatype',
  path: 'testjsondatatype',
  type: 'form',
  display: 'form',
  owner: '637b2e6b48c1227e60b1f910',
  components: [
    {
      label: 'Text Area',
      applyMaskOn: 'change',
      editor: 'ace',
      autoExpand: false,
      tableView: true,
      validateWhenHidden: false,
      key: 'textArea',
      type: 'textarea',
      as: 'json',
      input: true,
      id: 'eklvqa',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: true,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false,
        minLength: '',
        maxLength: '',
        pattern: '',
        minWords: '',
        maxWords: '',
      },
      conditional: {
        show: null,
        when: null,
        eq: '',
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
      mask: false,
      inputType: 'text',
      inputFormat: 'html',
      inputMask: '',
      displayMask: '',
      spellcheck: true,
      truncateMultipleSpaces: false,
      rows: 3,
      wysiwyg: false,
      fixedSize: true,
    },
    {
      type: 'button',
      label: 'Submit',
      key: 'submit',
      disableOnInvalid: true,
      input: true,
      tableView: false,
      id: 'e2cv2h',
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: true,
      refreshOn: '',
      redrawOn: '',
      modalEdit: false,
      dataGridLabel: true,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      calculateServer: false,
      widget: {
        type: 'input',
      },
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      conditional: {
        show: null,
        when: null,
        eq: '',
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: '',
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
      size: 'md',
      leftIcon: '',
      rightIcon: '',
      block: false,
      action: 'submit',
      theme: 'primary',
    },
  ],
  project: '66f26afae0c7ef9920ae59f6',
  created: '2024-09-24T12:30:26.148Z',
  modified: '2024-09-25T07:59:13.857Z',
  machineName: 'authoring-swfapsinuibaxma:testJsonDatatype',
};
