export default {
  mainForm: {
    _id: '69d78f1f2f4e367b7a474bac',
    title: 'eSubmissionsExt',
    name: 'eSubmissionsExt',
    path: 'esubmissionsext',
    type: 'form',
    display: 'wizard',
    owner: '69d8bf754fb544b7d9feb6cf',
    components: [
      {
        label: 'esubm',
        title: 'esubm',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'esubm',
        type: 'panel',
        components: [
          {
            label: 'Text Field',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textField',
            type: 'textfield',
            input: true,
          },
          {
            label: 'PMTA',
            tableView: true,
            form: '69d78f1f2f4e367b7a474ba5',
            useOriginalRevision: false,
            key: 'pmta',
            type: 'form',
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
    ],
    machineName: 'vjttrmymlaajomh:eSubmissionsExt',
    project: '69ae8d0efecdbaaaeaaebda8',
  },
  '69d78f1f2f4e367b7a474ba5': {
    _id: '69d78f1f2f4e367b7a474ba5',
    title: 'PMTA',
    name: 'pmta',
    path: 'pmta',
    type: 'form',
    display: 'wizard',
    components: [
      {
        label: 'PTMA panel 1',
        title: 'PTMA panel 1',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'ptmpPanel1',
        type: 'panel',
        input: false,
        tableView: false,
        components: [
          {
            label: 'PTMA panel 1 textfield',
            applyMaskOn: 'change',
            mask: false,
            tableView: false,
            delimiter: false,
            requireDecimal: false,
            inputFormat: 'plain',
            truncateMultipleSpaces: false,
            validateWhenHidden: false,
            key: 'ptmaPanel1TextF',
            type: 'number',
            input: true,
          },
          {
            label: 'Contacts',
            tableView: true,
            form: '69d78f1f2f4e367b7a474b9e',
            useOriginalRevision: false,
            clearOnHide: false,
            key: 'contacts',
            type: 'form',
            input: true,
          },
        ],
      },
    ],
    machineName: 'vjttrmymlaajomh:pmta',
    project: '69ae8d0efecdbaaaeaaebda8',
    created: '2026-04-09T11:35:59.135Z',
    modified: '2026-04-15T13:01:42.881Z',
  },
  '69d78f1f2f4e367b7a474b9e': {
    _id: '69d78f1f2f4e367b7a474b9e',
    title: 'PMTA Identification Information',
    name: 'pmtaIdentificationInformation',
    path: 'pmtaidentificationinformation',
    type: 'form',
    display: 'wizard',
    owner: '69d8b6f12f4e367b7a47cef3',
    components: [
      {
        label: ' Identification infpanel 1',
        title: ' Identification infor panel 1',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'idenInfPanel1',
        properties: {
          subsection: '1',
        },
        type: 'panel',
        components: [
          {
            label: 'Address',
            tableView: false,
            form: '69d78f1f2f4e367b7a474b82',
            lazyLoad: false,
            useOriginalRevision: false,
            clearOnHide: false,
            key: 'address',
            type: 'form',
            input: true,
          },
        ],
        input: false,
        tableView: false,
      },
      {
        label: 'Ident info panel 2',
        title: 'Ident info panel 2',
        breadcrumbClickable: true,
        buttonSettings: {
          previous: true,
          cancel: true,
          next: true,
        },
        navigateOnEnter: false,
        saveOnEnter: false,
        scrollToTop: false,
        collapsible: false,
        key: 'page2',
        type: 'panel',
        input: false,
        tableView: false,
        components: [
          {
            label: 'Text Field iden inf panel 2',
            applyMaskOn: 'change',
            tableView: true,
            validateWhenHidden: false,
            key: 'textFieldIdenInfPanel2',
            type: 'textfield',
            input: true,
            'widget.type': 'input',
          },
        ],
      },
    ],
    machineName: 'vjttrmymlaajomh:pmtaIdentificationInformation',
    project: '69ae8d0efecdbaaaeaaebda8',
  },
  '69d78f1f2f4e367b7a474b82': {
    _id: '69d78f1f2f4e367b7a474b82',
    title: 'adresss 4',
    name: 'adresss4',
    path: 'adresss4',
    type: 'form',
    display: 'form',

    owner: '69d8d1034fb544b7d9ff25fa',
    components: [
      {
        label: 'Country',
        widget: 'choicesjs',
        tableView: true,
        data: {
          values: [
            {
              label: 'a',
              value: 'a',
            },
            {
              label: 'b',
              value: 'b',
            },
          ],
          resource: 'country',
        },
        clearOnHide: false,
        validate: {
          required: true,
        },
        validateWhenHidden: false,
        key: 'country',
        type: 'select',
        input: true,
      },
      {
        type: 'button',
        label: 'Submit',
        key: 'submit',
        disableOnInvalid: true,
        input: true,
        tableView: false,
      },
    ],
    machineName: 'vjttrmymlaajomh:adresss4',
    project: '69ae8d0efecdbaaaeaaebda8',
    created: '2026-04-09T11:35:59.048Z',
    modified: '2026-04-10T10:29:23.946Z',
  },
};
