export default {
  title: 'Wizard Form',
  components: [
    {
      title: 'Page 1',
      label: 'Page 1',
      type: 'panel',
      key: 'page1',
      components: [
        {
          label: 'a',
          labelPosition: 'top',
          placeholder: '',
          description: '',
          tooltip: '',
          prefix: '',
          suffix: '',
          widget: {
            type: 'input'
          },
          inputMask: '',
          allowMultipleMasks: false,
          customClass: '',
          tabindex: '',
          hidden: false,
          hideLabel: false,
          showWordCount: false,
          showCharCount: false,
          mask: false,
          autofocus: false,
          spellcheck: true,
          disabled: false,
          tableView: true,
          modalEdit: false,
          multiple: false,
          persistent: true,
          inputFormat: 'plain',
          'protected': false,
          dbIndex: false,
          'case': '',
          encrypted: false,
          redrawOn: '',
          clearOnHide: true,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          allowCalculateOverride: false,
          validateOn: 'change',
          validate: {
            required: true,
            pattern: '',
            customMessage: '',
            custom: '',
            customPrivate: false,
            json: '',
            minLength: '',
            maxLength: '',
            strictDateValidation: false,
            multiple: false,
            unique: false
          },
          unique: false,
          errorLabel: '',
          key: 'a',
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: '',
            json: ''
          },
          customConditional: '',
          logic: [],
          attributes: {},
          overlay: {
            style: '',
            page: '',
            left: '',
            top: '',
            width: '',
            height: ''
          },
          type: 'textfield',
          input: true,
          refreshOn: '',
          inputType: 'text',
          id: 'eap4fh',
          defaultValue: ''
        },
        {
          label: 'b',
          labelPosition: 'top',
          placeholder: '',
          description: '',
          tooltip: '',
          prefix: '',
          suffix: '',
          widget: {
            type: 'input'
          },
          inputMask: '',
          allowMultipleMasks: false,
          customClass: '',
          tabindex: '',
          hidden: false,
          hideLabel: false,
          showWordCount: false,
          showCharCount: false,
          mask: false,
          autofocus: false,
          spellcheck: true,
          disabled: false,
          tableView: true,
          modalEdit: false,
          multiple: false,
          persistent: true,
          inputFormat: 'plain',
          'protected': false,
          dbIndex: false,
          'case': '',
          encrypted: false,
          redrawOn: '',
          clearOnHide: true,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          allowCalculateOverride: false,
          validateOn: 'change',
          validate: {
            required: true,
            pattern: '',
            customMessage: '',
            custom: '',
            customPrivate: false,
            json: '',
            minLength: '',
            maxLength: 4,
            strictDateValidation: false,
            multiple: false,
            unique: false
          },
          unique: false,
          errorLabel: '',
          key: 'b',
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: '',
            json: ''
          },
          customConditional: '',
          logic: [],
          attributes: {},
          overlay: {
            style: '',
            page: '',
            left: '',
            top: '',
            width: '',
            height: ''
          },
          type: 'textfield',
          input: true,
          refreshOn: '',
          inputType: 'text',
          id: 'eo1khi9',
          defaultValue: ''
        }
      ],
      input: false,
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      'protected': false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: false,
      refreshOn: '',
      redrawOn: '',
      tableView: false,
      modalEdit: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      widget: null,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: true,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false
      },
      conditional: {
        show: null,
        when: null,
        eq: ''
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: ''
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      tree: false,
      theme: 'default',
      breadcrumb: 'default',
      id: 'etrhlbe'
    },
    {
      title: 'Page 2',
      label: 'Page 2',
      type: 'panel',
      key: 'page2',
      components: [
        {
          label: 'c',
          labelPosition: 'top',
          placeholder: '',
          description: '',
          tooltip: '',
          prefix: '',
          suffix: '',
          widget: {
            type: 'input'
          },
          inputMask: '',
          allowMultipleMasks: false,
          customClass: '',
          tabindex: '',
          hidden: false,
          hideLabel: false,
          showWordCount: false,
          showCharCount: false,
          mask: false,
          autofocus: false,
          spellcheck: true,
          disabled: false,
          tableView: true,
          modalEdit: false,
          multiple: false,
          persistent: true,
          inputFormat: 'plain',
          'protected': false,
          dbIndex: false,
          'case': '',
          encrypted: false,
          redrawOn: '',
          clearOnHide: true,
          customDefaultValue: '',
          calculateValue: '',
          calculateServer: false,
          allowCalculateOverride: false,
          validateOn: 'change',
          validate: {
            required: false,
            pattern: '',
            customMessage: '',
            custom: '',
            customPrivate: false,
            json: '',
            minLength: '',
            maxLength: '',
            strictDateValidation: false,
            multiple: false,
            unique: false
          },
          unique: false,
          errorLabel: '',
          key: 'c',
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: '',
            json: ''
          },
          customConditional: '',
          logic: [],
          attributes: {},
          overlay: {
            style: '',
            page: '',
            left: '',
            top: '',
            width: '',
            height: ''
          },
          type: 'textfield',
          input: true,
          refreshOn: '',
          inputType: 'text',
          id: 'euovhcc',
          defaultValue: ''
        }
      ],
      input: false,
      placeholder: '',
      prefix: '',
      customClass: '',
      suffix: '',
      multiple: false,
      defaultValue: null,
      'protected': false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: false,
      refreshOn: '',
      redrawOn: '',
      tableView: false,
      modalEdit: false,
      labelPosition: 'top',
      description: '',
      errorLabel: '',
      tooltip: '',
      hideLabel: false,
      tabindex: '',
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: '',
      calculateValue: '',
      widget: null,
      attributes: {},
      validateOn: 'change',
      validate: {
        required: false,
        custom: '',
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false
      },
      conditional: {
        show: null,
        when: null,
        eq: ''
      },
      overlay: {
        style: '',
        left: '',
        top: '',
        width: '',
        height: ''
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      tree: false,
      theme: 'default',
      breadcrumb: 'default',
      id: 'eij9ua'
    }
  ],
};

