const form = {
  "type": "form",
  "components": [{
    "title": "Page 1",
    "label": "Page 1",
    "type": "panel",
    "key": "page1",
    "components": [{
      "label": "Number",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "delimiter": false,
      "requireDecimal": false,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "min": "",
        "max": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "step": "any",
        "integer": ""
      },
      "errorLabel": "",
      "key": "number",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "number",
      "input": true,
      "unique": false,
      "refreshOn": "",
      "dataGridLabel": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "id": "exvx54",
      "defaultValue": null
    }],
    "input": false,
    "placeholder": "",
    "prefix": "",
    "customClass": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "hidden": false,
    "clearOnHide": false,
    "refreshOn": "",
    "redrawOn": "",
    "tableView": false,
    "modalEdit": false,
    "dataGridLabel": false,
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "tooltip": "",
    "hideLabel": false,
    "tabindex": "",
    "disabled": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": null,
    "attributes": {},
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "conditional": {
      "show": null,
      "when": null,
      "eq": ""
    },
    "overlay": {
      "style": "",
      "left": "",
      "top": "",
      "width": "",
      "height": ""
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "properties": {},
    "allowMultipleMasks": false,
    "tree": false,
    "theme": "default",
    "breadcrumb": "default",
    "id": "er8pwjk"
  }, {
    "title": "Page 2",
    "label": "Page 2",
    "type": "panel",
    "key": "page2",
    "components": [{
      "label": "Text Field",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "inputMask": "",
      "allowMultipleMasks": false,
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "key": "textField",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textfield",
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "inputType": "text",
      "id": "ejmj41t",
      "defaultValue": null
    }],
    "input": false,
    "placeholder": "",
    "prefix": "",
    "customClass": "",
    "suffix": "",
    "multiple": false,
    "defaultValue": null,
    "protected": false,
    "unique": false,
    "persistent": false,
    "hidden": false,
    "clearOnHide": false,
    "refreshOn": "",
    "redrawOn": "",
    "tableView": false,
    "modalEdit": false,
    "dataGridLabel": false,
    "labelPosition": "top",
    "description": "",
    "errorLabel": "",
    "tooltip": "",
    "hideLabel": false,
    "tabindex": "",
    "disabled": false,
    "autofocus": false,
    "dbIndex": false,
    "customDefaultValue": "",
    "calculateValue": "",
    "calculateServer": false,
    "widget": null,
    "attributes": {},
    "validateOn": "change",
    "validate": {
      "required": false,
      "custom": "",
      "customPrivate": false,
      "strictDateValidation": false,
      "multiple": false,
      "unique": false
    },
    "conditional": {
      "show": null,
      "when": null,
      "eq": ""
    },
    "overlay": {
      "style": "",
      "left": "",
      "top": "",
      "width": "",
      "height": ""
    },
    "allowCalculateOverride": false,
    "encrypted": false,
    "showCharCount": false,
    "showWordCount": false,
    "properties": {},
    "allowMultipleMasks": false,
    "tree": false,
    "theme": "default",
    "breadcrumb": "default",
    "id": "ew0o7w"
  }],
  "title": "wizard first page subm test",
  "display": "wizard",
  "name": "wizardFirstPageSubmTest",
  "path": "wizardfirstpagesubmtest",
};

const submission = {
  data: {
    number: 111,
    textField: 'test'
  }
};

export default {
  form: form,
  submission: submission,
};
